### ISSUE TITLE
老哥，你这个对于不同项目之间的样式污染是如何处理的呢？

### ISSUE THREAD

**Issue by Huansheng1** [lanaqi-opensource/aqi-microapp#1]
按照官网接入的话，对于使用了[ng material](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/angular?id=_2%e3%80%81angularmaterial%e7%bb%84%e4%bb%b6%e5%ba%93%e6%a0%b7%e5%bc%8f%e5%a4%b1%e6%95%88) 或者 ngbootstrap 之类的组件库弹窗等功能，如果不关闭样式禁用的话是会导致弹框样式异常的，你这个开源仓库对这里做了特殊处理么？
如果我使用的话，直接关闭样式隔离将会导致不同项目之间的样式类互相污染，进而导致样式变形的吧？
目前`angular`对于`style.less`之类的全局样式并没有增加相应的哈希属性值来保证避免污染其他应用。
如果我开启keep-alive就会有这个问题。
另外是否也会开启几个子应用切换（keep-alive模式）时，第三个应用以后会出现`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined`这种报错

**Comment by lanmingle** [comment]
目前还处于开发阶段，不建议直接使用到生产上，另外对于隔离这些没有特别处理，只是对官方上进行封装，简化使用，对于隔离话建议开启沙盒模式。

**Comment by lanmingle** [comment]
我两天有空折腾一下其它UI组件上去，看下有啥办法做隔离呗！目前基于官方 0.8.5 开启 keep-alive 还是遇到一些奇葩的问题的，简单来说官方的库还是不怎么稳定。
